### ISSUE TITLE
Memory Widget not filtering based on values

### ISSUE THREAD

**Issue by computeronix** [munkireport/munkireport-php#290] opened 2015-08-16 03:13 UTC
In the Installed memory widget if you click on any of the values it takes you to the hardware table with all values listed.

For example if you click 4GB view it shows all memory items instead of just machines with 4GB.

**Comment by bochoven** [comment] 2015-08-16 08:21
Duplicate of #232

**Closed by bochoven** 2015-08-16 08:21 UTC
Labels: duplicate
