### ISSUE TITLE
SQLite db size error

### ISSUE THREAD

**Issue by brahmafear** [munkireport/munkireport-php#1176] opened 2018-11-07 13:05 UTC
New install of latest tar ball release of munkireport (also tried git version if that is different).  OSX Mojave.  PHP 7.1.19.  Using built in apache2 (not Server.app).  App/db directory writeable by _www user.  PHP and Rewrite modules enabled in httpd.conf.  Config.php entries added for user account and debug=true.  

When attempting to update database, receive a JSON parse error.  Db.sqlite file is created.  Tried Apache restart.  See screenshot.  

![e900e97c-19e6-4f3a-b05c-cac8976dfe5b](https://user-images.githubusercontent.com/5796940/48133128-c6380580-e263-11e8-92a2-e26cc906f243.jpeg)

**Comment by bochoven** [comment] 2018-11-07 13:11
That message is the result of an underlying error. Could you check this url:

```
https://yourmunkireportserver/index.php?/database/migrate
```

**Comment by brahmafear** [comment] 2018-11-07 15:15
Receiving this from that URL:

Fatal error: Cannot declare class Detectx, because the name is already in use in /Users/Shared/Munki/munkireport-php/app/modules/detectx/migrations/2018_08_17_094300_detectx.php on line 26

**Comment by bochoven** [comment] 2018-11-07 15:35
That bug is being fixed right now. 3.2.5 should fix that.

**Comment by brahmafear** [comment] 2018-11-07 15:41
Excellent.  Any idea of release timeframe?

**Comment by bochoven** [comment] 2018-11-07 17:51
3.2.5 is released, does it solve your issue?

**Comment by brahmafear** [comment] 2018-11-07 18:01
Partial.  

I nuked and installed fresh 3.2.5.  I was able to run database upgrade and get lots of messages about migrations, but this SQL error showed at bottom:

SQLSTATE[HY000]: General error: 17 database schema has changed (SQL: insert into "migrations" ("migration", "batch") values (2017_02_09_231419_bluetooth, 1))

Also, the system status page is showing another JSON parse error.  

![screen shot 2018-11-07 at 1 01 17 pm](https://user-images.githubusercontent.com/5796940/48150640-4030b480-e28d-11e8-86bf-e1a3020da969.png)

**Comment by bochoven** [comment] 2018-11-07 19:36
In my experience the 'database schema has changed' message clears up if you do a second migration

**Comment by brahmafear** [comment] 2018-11-07 19:58
I do see that.  Getting "Nothing to migrate" now when clicking Update on database page.  

Still getting that error on System Status page though.

**Comment by bochoven** [comment] 2018-11-08 20:31
What does `/index.php?/system/DataBaseInfo` return?

**Comment by brahmafear** [comment] 2018-11-08 22:16
Updated to 3.2.6.

Getting this at the page you listed:

*Notice*: Undefined index: page_count in
*/Users/Shared/Munki/munkireport/app/lib/munkireport/Database.php* on line
*180*
{"db.driver":"sqlite","db.connectable":true,"db.writable":true,"db.size":0,"error":"","version":"3.15.1"}

**Comment by bochoven** [comment] 2018-11-08 22:37
I cannot reproduce your issue, could you change the size calculation function in `/Users/Shared/Munki/munkireport/app/lib/munkireport/Database.php`

to

```php
    public function sizeSQLite()
    {
        $result = $this->fetchOne('PRAGMA PAGE_SIZE');
        $page_size = $result['page_size'];
        $result = $this->fetchOne('PRAGMA PAGE_COUNT');
        var_dump($result);
        $page_count = $result['page_count'];
        return $page_size * $page_count / 1024.0/1024.0;
    }
```

and post the output again?

**Comment by brahmafear** [comment] 2018-11-08 22:49
array(2) { ["PAGE_COUNT"]=> string(4) "1143" [0]=> string(4) "1143" }
*Notice*: Undefined index: page_count in
*/Users/Shared/Munki/munkireport/app/lib/munkireport/Database.php* on line
*181*
{"db.driver":"sqlite","db.connectable":true,"db.writable":true,"db.size":0,"error":"","version":"3.15.1"}

**Comment by bochoven** [comment] 2018-11-08 22:53
So this will probably fix your issue:

```
    public function sizeSQLite()
    {
        $result = $this->fetchOne('PRAGMA PAGE_SIZE');
        $page_size = $result[0];
        $result = $this->fetchOne('PRAGMA PAGE_COUNT');
        $page_count = $result[0];
        return $page_size * $page_count / 1024.0/1024.0;
    }
```

**Comment by brahmafear** [comment] 2018-11-08 22:57
Confirmed.  Working.  A case sensitivity issue?

Something for me to re-apply whenever I update or will some sort of change
be worked into next release?

**Comment by brahmafear** [comment] 2018-11-08 22:57
Also, thank you for such prompt resolution!!

**Comment by bochoven** [comment] 2018-11-08 22:58
It will be in the next release

**Closed** 2018-11-21 09:57 UTC
Labels: fixed in wip
