### ISSUE TITLE
Only "Normal" condition listed in "Battery Condition" widget

### ISSUE THREAD

**Issue by markomili** [munkireport/munkireport-php#697] opened 2017-03-24 08:21 UTC
Listings > Batteries shows that we have Normal, "Service Now" and "Replace Now" batteries. However, only Normal batteries are listed in Reports > "Power Report" in "Battery Condition" widget.

**Comment by tuxudo** [comment] 2017-03-24 12:40
I'm not able to reproduce this. What do you see when you go to /munkireport-php/index.php?/module/power/conditions ?

**Comment by markomili** [comment] 2017-03-24 18:46
I see {"normal":169,"soon":0,"service":0,"now":0,"missing":0}

 

SELECT `condition`, COUNT(*) FROM `power` GROUP BY `condition` gives:

 

(blank) 1

Normal 169

ReplaceNow 5

ServiceBattery 9

**Comment by tuxudo** [comment] 2017-03-24 19:33
This should be fixed with PR #698. Was caused by OS X reporting different values for the battery condition.

**Closed** 2017-03-30 15:32 UTC
