### ISSUE TITLE
New Munki Client Installation Doc to Create Munki Pkg Step 1 is Incomplete

### ISSUE THREAD

**Issue by jhowe-sgs** [munkireport/munkireport-php#244] opened 2015-04-28 23:14 UTC
The updated Step # 1 in the new docs/setup.md file for creating a munkireport-N.N.N.pkg is incomplete.

Missing a pipe command, or some other command line string.

**Comment by bochoven** [comment] 2015-04-29 05:51
Not sure what you mean, Bash -c  executes the curl'd script.

**Comment by jhowe-sgs** [comment] 2015-04-29 17:15
You are correct. I had a typo.

There is a warning with the mktemp command:

100 14369    0 14369    0     0  1196k      0 --:--:-- --:--:-- --:--:-- 1754k

mktemp: too few X's in template ‘mrpkg’

Preparing /install_root/usr/local/munki/ and /Library/Preferences/MunkiReport

Thanks

**Comment by bochoven** [comment] 2015-04-30 22:12
On what OS version is `mktemp -d -t mrpkg` failing?

**Comment by jhowe-sgs** [comment] 2015-04-30 23:45
10.9.5

From the mktemp man page:

"The template may be any file name with some number of `Xs' appended to it, for example /tmp/temp.XXXX. The trailing `Xs' are replaced with the current process number and/or a unique letter combination."

From testing, it's needs at least three on OS X 10.9.5:

jhowe@wenchang:~
$ mktemp -d -t mrpkg
mktemp: too few X's in template ‘mrpkg’

jhowe@wenchang:~
$ mktemp -d -t mrpkg.X
mktemp: too few X's in template ‘mrpkg.X’

jhowe@wenchang:~
$ mktemp -d -t mrpkg.XX
mktemp: too few X's in template ‘mrpkg.XX’

jhowe@wenchang:~
$ mktemp -d -t mrpkg.XXX
/var/folders/zs/mjw_m4b934j59t1fsk6kp8kdz6k7j_/T/mrpkg.0Vl

Note: "X"s are case sensitive. Lower case "x" doesn't work.

Thanks

**Comment by bochoven** [comment] 2015-07-22 13:39
I can't reproduce this, and I got no other reports. Closing

**Closed by bochoven** 2015-07-22 13:39 UTC
Labels: cannot reproduce
