### ISSUE TITLE
timemachine module doesn't work in macOS Mojave 

### ISSUE THREAD

**Issue by HaniAlshikh** [munkireport/munkireport-php#1238] opened 2019-03-19 12:23 UTC
I think the problem is apple SIP ([System Integrity Protection](https://support.apple.com/en-us/HT204899)) as mentioned [here](https://discussions.apple.com/thread/8592971) 

but i will keep researching in case it's something else and maybe find a solution on my way

**Comment by tuxudo** [comment] 2019-03-19 13:34
I'm not able to reproduce this. The module's version wasn't incremented when the latest PR was merged in. I upped it. Try updating the module(s) and test it again.

**Comment by HaniAlshikh** [comment] 2019-03-19 13:59
the double checked the timemachine model and it's up to date with [munkireport/timemachine](https://github.com/munkireport/timemachine)

i'm using MunkiReport Version 4.0.1.3685

Running the [timemachine](https://github.com/munkireport/timemachine/blob/master/scripts/timemachine) script produces an empty plist 
[timemachine.plist.txt](https://github.com/munkireport/munkireport-php/files/2983646/timemachine.plist.txt)

and this is the com.apple.TimeMachine.plist on my test device
[com.apple.TimeMachine.plist.txt](https://github.com/munkireport/munkireport-php/files/2983670/com.apple.TimeMachine.plist.txt)

according to my tests, i was able to read the plist only with defaults, reading it with cat for example comes back with Operation not permitted even with root

with FoundationPlist.readPlist:

```python
Traceback (most recent call last):
  File "timemachine.py", line 126, in <module>
    main()
  File "timemachine.py", line 119, in main
    info = get_time_machine()
  File "timemachine.py", line 44, in get_time_machine
    out = FoundationPlist.readPlist('/Library/Preferences/com.apple.TimeMachine.plist')
  File "/usr/local/munki/munkilib/FoundationPlist.py", line 84, in readPlist
    raise NSPropertyListSerializationException(errmsg)
munkilib.FoundationPlist.NSPropertyListSerializationException: stream had too few bytes in file /Library/Preferences/com.apple.TimeMachine.plist
```
i'm working on a soloution right now using defaults.

Thanks for helping

**Comment by tuxudo** [comment] 2019-03-19 14:07
Defaults cannot work properly with that script. Is this an upgrade to 10.14 or a new install? The cache file that is used is `/usr/local/munki/preflight.d/cache/timemachine.plist`, not `/usr/local/munki/preflight.d/cache/timemachine.plist.txt`

**Comment by HaniAlshikh** [comment] 2019-03-19 14:11
"Defaults cannot work properly with that script"
i know, I'm trying to create a tmp plist file with defaults and then pass it to the FoundationPlist

"timemachine.plist.txt"
i added .txt because GitHub don't allow .plist files

**Comment by HaniAlshikh** [comment] 2019-03-20 09:15
still far from perfect and I'm working on it, but any suggestions are welcomed.
[timemachine_fix.txt](https://github.com/munkireport/munkireport-php/files/2987333/timemachine_fix.txt)

Aslo @tuxudo is the script working for you on Mojave?
this is how i fixed it for now

```python
.
.
def mojave_fix(timemachine_plist):
    """Read the TimeMachine plist with defaults, serve it to FoundationPlist"""
    tmp_plist = '/var/tmp/tinemachine.plist'
    cmd = ['defaults', 'read', timemachine_plist]
    proc = subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE
    )
    (out, err) = proc.communicate()
    try:
        with open (tmp_plist, 'w+') as tmp:
            tmp.write(out)
    except Exception:
        return timemachine_plist
    return tmp_plist


def get_time_machine():
    
    # Read in com.apple.TimeMachine.plist for processing 
    timemachine_plist = '/Library/Preferences/com.apple.TimeMachine.plist'
    if getOsVersion > 13:
        timemachine_plist = mojave_fix(timemachine_plist)
    try:
        out = FoundationPlist.readPlist(timemachine_plist)
    except Exception:
        return {}
.
.
```

**Comment by tuxudo** [comment] 2019-03-20 09:58
Yes, it is still working correctly for me using the script that is in the module. Are you having these problems on a fresh install of 10.14 or an upgrade to 10.13?

**Comment by HaniAlshikh** [comment] 2019-03-20 10:00
fresh install

**Comment by HaniAlshikh** [comment] 2019-03-20 10:24
i did another fresh install and got the same results, anyway I'm having too many problems with time machine for my backup needs, so I'm moving to another tool.

My fix is still working @tuxudo if you want i can make a PR.

My only wonder is, that it's working for you @tuxudo. I'm using Profile Manager (it's awful i know) to manage my devices, it could be the one responsible for the problem.

**Comment by tuxudo** [comment] 2019-03-25 19:27
I tested this on a machine that has a fresh install of 10.14, still working correctly. My guess is that your /Library/Preferences/com.apple.TimeMachine.plist file is either empty or the profiles are breaking the script. I do know that the timemachine script does not respect preferences set via a profile. That is on my list of things to update. Will look into this tomorrow.

**Comment by HaniAlshikh** [comment] 2019-03-25 19:39
Thank you for taking the time.
> com.apple.TimeMachine.plist file is either empty

we can take this one out of the reasons, cuz i already tested it in all ways known to me and my "fix" wouldn't work if the timemachine plist is empty

> the timemachine script does not respect preferences set via a profile . 

can you give a little more details on that.

**Comment by tuxudo** [comment] 2019-03-25 20:04
The script does not use things set in profiles. Only things that are on in the preference file itself.

**Comment by HaniAlshikh** [comment] 2019-03-25 20:21
Ok, i will wait untell you take a look into it, cuz this for me take us back to the fact, that the /Library/Preferences/com.apple.TimeMachine.plist file exists for me and contains data, which what FoundationPlist.readPlist requires and off curse permissions, which is making the whole problem in the first place.

**Comment by tuxudo** [comment] 2019-03-25 20:25
What version of MR are you using? If newer than 4.0, have you updated the timemachine module?

**Comment by HaniAlshikh** [comment] 2019-03-25 20:28
4.0.1.3685 and yes, i even used compose to double check

**Comment by tuxudo** [comment] 2019-03-25 20:34
It's strange because the error you posted above don't match up with the lines of the script. Please verify that the timemachine script on one of your 10.14 clients matches the one located here: https://github.com/munkireport/timemachine/blob/master/scripts/timemachine

**Comment by HaniAlshikh** [comment] 2019-03-25 20:38
I'm almost 100% sure it's the same, but i will double check tomorrow at work.

**Comment by HaniAlshikh** [comment] 2019-03-26 08:14
Ok, i double checked and the error is still there using the same script as
https://github.com/munkireport/timemachine/blob/master/scripts/timemachine

```python
Traceback (most recent call last):
  File "timemachine", line 104, in <module>
    main()
  File "timemachine", line 97, in main
    info = get_time_machine()
  File "timemachine", line 21, in get_time_machine
    out = FoundationPlist.readPlist('/Library/Preferences/com.apple.TimeMachine.plist')
  File "/usr/local/munki/munkilib/FoundationPlist.py", line 84, in readPlist
    raise NSPropertyListSerializationException(errmsg)
munkilib.FoundationPlist.NSPropertyListSerializationException: stream had too few bytes in file /Library/Preferences/com.apple.TimeMachine.plist
```

the reason, why the numbers didn't match last time is that i removed the try, except statement to get the error

**Comment by tuxudo** [comment] 2019-03-26 10:49
Try the script located here: https://github.com/tuxudo/timemachine/blob/profiles_fix/scripts/timemachine 

Also, could we move this conversation to the munkireport channel of the MacAdmins Slack (https://macadmins.herokuapp.com/)?

**Comment by HaniAlshikh** [comment] 2019-03-26 11:20
Boom, it works 
<img width="473" alt="timemachine_working" src="https://user-images.githubusercontent.com/39484930/54993153-7d3ddf00-4fc1-11e9-9a5a-69dce56659d6.png">

Thanks a lot.

**Comment by tuxudo** [comment] 2019-03-26 11:21
Wonderful, thank you. I'll make a PR to the main module for this.

**Comment by HaniAlshikh** [comment] 2019-03-26 11:24
Great, i think we can close this issue for now. 👍

**Closed** 2019-03-31 12:00 UTC

**Comment by loopway** [comment] 2019-05-23 09:43
can you please link the PR? ran into the same issues and could not find it.

**Comment by loopway** [comment] 2019-05-23 09:50
never mind, found it: https://github.com/munkireport/timemachine/pull/2
