### ISSUE TITLE
Munkireport 2.6.0-beta.1 - Blank Pages

### ISSUE THREAD

**Issue by mjonesrsn** [munkireport/munkireport-php#329] opened 2015-10-07 19:23 UTC
OS X 10.11 (15A284) with OS X Server.app 5.0.4

Safari 9.0 (11601.1.56)

Shows blank page (only see the top frame) for Active clients in Chrome and Safari. Safari, I can see the other pages, but all blank pages in Chrome.

**Comment by bochoven** [comment] 2015-10-07 19:31
I think for clarity you should add each issue separately.

**Comment by mjonesrsn** [comment] 2015-10-07 19:34
Will do. I will create the others later.

**Comment by bochoven** [comment] 2015-10-07 19:46
Can't reproduce your issue on Chrome 45.0.2454.101 Could you take a look at the javascript console?

**Comment by rickheil** [comment] 2015-10-08 11:33
Also getting blank pages after update to 2.6 beta 1. Here's a screenshot of the error console: 
<img width="1285" alt="screenshot 2015-10-08 07 31 39" src="https://cloud.githubusercontent.com/assets/8959676/10365116/bcaa2626-6d8e-11e5-903f-744b1ffdde51.png">

Browser is on Safari 9.0 on an OS X 10.11 machine.

**Comment by bochoven** [comment] 2015-10-08 13:47
Could you turn on debugging in config.php and see if it shows more errors?

**Comment by rickheil** [comment] 2015-10-08 13:58
Turned on debugging, no additional output.

**Comment by bochoven** [comment] 2015-10-08 14:00
Could you click one of the failing links in the error console: 
<code>
https://mun....index.php>clients/get_data/...
</code>

**Comment by rickheil** [comment] 2015-10-08 14:04
That returns: 
Parse error: parse error in /Library/Server/Web/Data/Sites/munkireports.partnersandsimons.com/app/modules/disk_report/disk_report_model.php on line 32

**Comment by bochoven** [comment] 2015-10-08 14:10
Ok found it, an unresolved merge conflict.. Fixed in 7a84a610da01afb4514ded0803b92d138027f99a

**Closed** 2015-10-08 14:10 UTC

**Comment by rickheil** [comment] 2015-10-08 14:11
Confirmed fixed. This also resolved another issue I had where the free disk space widget on the dashboard was blank. Thanks!

**Comment by bochoven** [comment] 2015-10-08 14:12
Thanks for reporting!

**Comment by mjonesrsn** [comment] 2015-10-08 14:34
Thanks for figuring this out guys! Sorry for not responding, trying to fix another issue.
