### ISSUE TITLE
Events filter doesn't show removals?

### ISSUE THREAD

**Issue by bryanzak** [munkireport/munkireport-php#486] opened 2016-05-11 14:24 UTC
I have some munki packages which are managed uninstalls or autoremove and while removals show up i the munki logs, they do not show up in the munkireport events widget - only installs.

**Comment by gmarnin** [comment] 2017-05-15 16:05
Duplicate of #763 and fixed with https://github.com/munkireport/munkireport-php/commit/714174c13b117ea7ae6dd241ae75c006dc400f6b

**Closed** 2017-05-15 16:33 UTC
Labels: enhancement
